### ISSUE TITLE
Can't save the Habit

### ISSUE THREAD

**Issue by Centauro2000** [Glitchy-Tozier/githo#23]
If the last two levels of an habit project are empty, the project is not saved, no matter if the cursor is located un the last filled le el por how many times the green button is pressed. 

AND you lost al the inputs written :\

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report! Could you give me some more information?

1. Were you trying to add a new habit?
1. Do you mean the text-boxes of the last two levels were empty when you saved?
1. How did you even manage to get the last two levels empty? I thought I made that almost impossible!
1. What exactly happened when you pressed the green button? Did an empty habit get saved?

**Comment by Centauro2000** [comment]
Were you trying to add a new habit?
    Yes, I was

    Do you mean the text-boxes of the last two levels were empty when you saved?
    Exactly

    How did you even manage to get the last two levels empty? I thought I made that almost impossible!
   I deleted the text of the last two tex-boxes because I was editng and re arranging the levels of the habit.
   Then, I tried to figure out how to delete thos two las levels but I did not find the way.

    What exactly happened when you pressed the green button? 
    All remained the same, No change, 

   Did an empty habit get saved?
   No. there wasn´t an empty habit. There was only the habit I had created before.

**Comment by Glitchy-Tozier** [comment]
I'll start working on two different fixes.

>> Did an empty habit get saved?
>
> No. there wasn´t an empty habit. There was only the habit I had created before.

Did the habit-editing-screen close itself when you pressed save or did you manually return to the previous screen?

**Comment by Centauro2000** [comment]
Did the habit-editing-screen close itself when you pressed save or did you manually return to the previous screen?

In fact, none of them. The habit-editing-screen remained unchanged, and no noticeable changes was perceptible.

BTW, I would like to suggest the possibility that the user were capable to edit the levels as a whole, I mean, to delete and re-arragenge the levels as floting windows.

IMHO this is a unique app because solve the important issue of building habits. Hence, it has a great potential!

**Comment by Glitchy-Tozier** [comment]
I am pretty sure the issue you were facing was that there were faulty TextFields. While they were highlighted, they didn't grab your attention. Thus you thought everything was fine while actually the habit never was saved.
If the Habit had been saved (if the validation was successful), the screen would have closed automatically.

In last few commits, I improved usability of the habit-editing-screen:

1. If you try to save and there's invalid TextFields, they will scroll on-screen and get focused
2. You can reordering levels/comments
3. You can add a new level/comment below your current one
4. You can easily delete any of the comments
5. Other small improvements such as [making it easier to jump from one TextField to the next](https://github.com/Glitchy-Tozier/githo/commit/78a32935cdc0ad440d2d1c544903c426d0f6becf)

These changes will be included in **version 1.3.4**, which will probably be released tomorrow. It should arrive in F-Droid in 3-5 days.

As this problem seems to be resolved, I'll close this issue. Should there be any other ideas/comments on your part, you can reopen the issue and post them here.  :)
