### ISSUE TITLE
Multiple active habits at a time.

### ISSUE THREAD

**Issue by Long-FA** [Glitchy-Tozier/githo#6]
Right now there can only be one active habit at a time. If you favorite a new habit, the progress of the currently active one will be lost. This poses a problem for users who want to work on multiple habits together.
My suggestion: Scrap the "favorite" idea altogether. All habits in the "List of habits" will be active and tracked by default. Tapping on a habit in the List of habits will bring up the progression screen. Holding the habit in the "List of habits" will bring up a hamburger menu will the choice to Edit or Delete.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to fill in this issue.

I suspected that this will come up eventually, but at the moment, i don't plan on adding this feature.

It's really tempting, but my end-goal is to make this an app for learning habits that stick with you. In my experience, trying to acquire multiple habits just doesn't work and makes the whole thing unstable. When you in with one habit (on a particular day), it's demotivating and makes it harder to continue with the other habits. After a period of being unproductive, it's even harder to get going when you know you have multiple difficult things to do.

This is why I don't plan on adding this feature, I hope you understand.

**Comment by KyleFN** [comment]
Your experience isn't the same as others. I've been creating and managing new habits for years and I've learned that there's other factors at play such as: how easy are your levels and the steps between them, how much experience do you have with creating habits and is the habit standalone or is it chained to another long-standing existing habit?

Since this app ignores any other factor other than "the amount of active habits" this makes it useless to anyone except those who are brand new to creating habits, and even those individuals can soon outgrow the app.
